---

- name: Install Java 1.7 and some basic dependencies
  yum: name={{item}} state=present
  sudo: yes
  with_items:
    - unzip
    - java-1.6.0-openjdk-devel.x86_64

- name: Add user "jboss"
  sudo: yes
  user: name=jboss

- name: extract jboss zip
  sudo: yes
  command: chdir=/usr/local /usr/bin/unzip -q /srv/playbooks/files/jboss-eap-{{ jboss_version }}.zip
           creates=/usr/local/{{ jboss_dir }}

- name: Link install directory
  sudo: yes
  command: chdir=/usr/local /bin/ln -sf {{ jboss_dir }} jbossas_intranet
           creates=/usr/local/jbossas_intranet

- name: Create log directory
  sudo: yes
  command: chdir=/usr/local/jbossas_intranet /bin/mkdir domain/log
           creates=/usr/local/jbossas_intranet/domain/log

- name: Create servers directory
  sudo: yes
  command: chdir=/usr/local/jbossas_intranet /bin/mkdir domain/servers
           creates=/usr/local/jbossas_intranet/domain/servers

- name: Change ownership of JBoss installation
  sudo: yes
  file: path=/usr/local/jbossas_intranet/ owner=jboss state=directory recurse=yes

- name: Prefill JBoss CLIs
  template: src=add-ds-eee.cli.j2 dest=/home/vagrant/add-ds-eee.cli
  template: src=add-ds-aaa.cli.j2 dest=/home/vagrant/add-ds-aaa.cli
  register: cli_generation


- name: Run CLI files to domain
  command: /bin/echo "running cli files against domain"
  when: cli_generation.changed
  























#- name: Starts JBoss
#  remote_user: jboss
#  command: chdir=/usr/local/jbossas_intranet/bin /bin/sh domain.sh

# add basic jboss admin user, either through add-user.sh or templating mgmt-user.properties
#   => is it possible?
#   => http://marvelley.com/blog/2014/04/23/handling-interactive-ansible-tasks/
# put oracle module in place
# put other local modifications in place
# put init scripts in place
# run jboss-cli files
